2024-11-01 15:06:51,034 ERROR: Exception on /watchVideo [GET] [in C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\run.py", line 119, in watch_video
    render_template("watchVideo.html", data=send_data)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: watchVideo.html
2024-11-01 15:15:51,525 ERROR: Exception on /watchVideo [GET] [in C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\run.py", line 121, in watch_video
    render_template("watchVideo.html", data=send_data)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\app\templates\watchVideo.html", line 1, in top-level template code
    {% extends "format.html" %}
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\app\templates\format.html", line 68, in top-level template code
    {% block body %}
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\app\templates\watchVideo.html", line 45, in block 'body'
    <video src="{{ url_for('static', filename='video/asmr/' + data.videoPaths[0]) }}" controls autoplay id="mainVideo"></video>
jinja2.exceptions.UndefinedError: list object has no element 0
2024-11-01 15:17:43,960 ERROR: Exception on /watchVideo [GET] [in C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\run.py", line 100, in watch_video
    render_template("watchVideo.html", data=send_data)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\user\PycharmProjects\MyUtilProject\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\app\templates\watchVideo.html", line 1, in top-level template code
    {% extends "format.html" %}
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\app\templates\format.html", line 68, in top-level template code
    {% block body %}
  File "C:\Users\user\PycharmProjects\MyUtilProject\MyApp\FlaskApp\app\templates\watchVideo.html", line 45, in block 'body'
    <video src="{{ url_for('static', filename='video/asmr/' + data.videoPaths[0]) }}" controls autoplay id="mainVideo"></video>
jinja2.exceptions.UndefinedError: list object has no element 0
